# Generated by Django 4.2.7 on 2025-09-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Patient ID (PAT123, etc.)', max_length=20)),
                ('patient_name', models.CharField(help_text='Patient name', max_length=100)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('PRIVATE', 'Private Room'), ('ICU', 'Intensive Care Unit'), ('MATERNITY', 'Maternity Ward'), ('PEDIATRIC', 'Pediatric Ward'), ('SURGERY', 'Surgical Ward')], max_length=15)),
                ('bed_number', models.CharField(help_text='Bed identifier (A1, B2, etc.)', max_length=10)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Patient Admitted'), ('DISCHARGED', 'Patient Discharged'), ('TRANSFERRED', 'Transferred to Another Ward')], default='ADMITTED', max_length=15)),
                ('admission_notes', models.TextField(help_text='Notes from admission')),
                ('discharge_notes', models.TextField(blank=True, help_text='Notes from discharge', null=True)),
                ('daily_ward_fee', models.DecimalField(decimal_places=2, help_text='Daily charge for this ward type', max_digits=10)),
                ('attending_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='ward_assignments_doctor', to=settings.AUTH_USER_MODEL)),
                ('primary_nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='ward_assignments_primary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ward_assignments',
                'ordering': ['-admission_date'],
                'indexes': [models.Index(fields=['patient_id'], name='ward_assign_patient_cde8da_idx'), models.Index(fields=['ward_type', 'status'], name='ward_assign_ward_ty_979ff2_idx'), models.Index(fields=['bed_number'], name='ward_assign_bed_num_7647e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(help_text='Patient ID (PAT123, etc.)', max_length=20)),
                ('patient_name', models.CharField(help_text='Patient name for quick reference', max_length=100)),
                ('service_type', models.CharField(choices=[('INJECTION', 'Injection/IV'), ('WOUND_CARE', 'Wound Dressing'), ('VITAL_SIGNS', 'Vital Signs Monitoring'), ('MEDICATION_ADMIN', 'Medication Administration'), ('PATIENT_CARE', 'General Patient Care'), ('WARD_ROUND', 'Ward Round Assistance'), ('EMERGENCY_CARE', 'Emergency Nursing Care')], max_length=20)),
                ('service_description', models.TextField(help_text='Detailed description of service provided')),
                ('vital_signs', models.JSONField(blank=True, help_text='BP, Temperature, Pulse, etc. if applicable', null=True)),
                ('medications_given', models.TextField(blank=True, help_text='Medications administered', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('scheduled_at', models.DateTimeField(help_text='When service was scheduled')),
                ('started_at', models.DateTimeField(blank=True, help_text='When service actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When service was completed', null=True)),
                ('nurse_notes', models.TextField(blank=True, help_text='Nurse observations and notes', null=True)),
                ('patient_response', models.TextField(blank=True, help_text='How patient responded to service', null=True)),
                ('billed_to_finance', models.BooleanField(default=False, help_text='Whether this service has been billed')),
                ('assigned_nurse', models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_services_assigned', to=settings.AUTH_USER_MODEL)),
                ('supervised_by', models.ForeignKey(blank=True, help_text='Senior nurse or doctor supervision', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_services_supervised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nursing_services',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['patient_id'], name='nursing_ser_patient_40c9c4_idx'), models.Index(fields=['service_type', '-scheduled_at'], name='nursing_ser_service_ea0e7f_idx'), models.Index(fields=['status', '-scheduled_at'], name='nursing_ser_status_5472fa_idx'), models.Index(fields=['assigned_nurse', '-scheduled_at'], name='nursing_ser_assigne_7c78ac_idx')],
            },
        ),
    ]
