# Generated by Django 4.2.7 on 2025-09-04 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text='Auto-generated format: PAT1, PAT123, or PAT-A1B2C3D4', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Patient ID must be in format: PAT1, PAT123, or PAT-A1B2C3D4', regex='^PAT([1-9][0-9]*|[A-F0-9]{8})$')]),
        ),
    ]
