# Generated by Django 4.2.7 on 2024-01-15 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(
                choices=[('NORMAL', 'Normal Patient'), ('NHIF', 'NHIF Insured Patient')],
                default='NORMAL',
                help_text='Normal patient pays fees, NHIF patient has insurance coverage',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='patient',
            name='nhif_card_number',
            field=models.CharField(
                blank=True,
                help_text='NHIF insurance card number (required for NHIF patients)',
                max_length=20,
                null=True
            ),
        ),
    ]