# Generated by Django 4.2.7 on 2025-09-29 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_add_nhif_support_and_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, help_text='Patient occupation/job', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse_rate',
            field=models.IntegerField(blank=True, help_text='Pulse rate (beats per minute)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
