# Generated by Django 4.2.7 on 2025-09-30 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_add_occupation_and_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', help_text='First name (stored in uppercase)', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', help_text='Last name (stored in uppercase)', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(default='', help_text='Middle name (stored in uppercase)', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_category',
            field=models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('INPATIENT', 'Inpatient')], default='OUTPATIENT', help_text='Whether patient is admitted (inpatient) or visiting (outpatient)', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(help_text='Auto-generated from first, middle, and last names', max_length=100),
        ),
    ]
