# Generated by Django 4.2.7 on 2025-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_first_name_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_status',
            field=models.CharField(choices=[('REGISTERED', 'Just Registered'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('WITH_DOCTOR', 'Currently with Doctor'), ('PENDING_LAB_PAYMENT', 'Pending Lab Payment'), ('LAB_PAID', 'Lab Payment Completed'), ('WAITING_LAB', 'Waiting for Lab Tests'), ('IN_LAB', 'Currently in Laboratory'), ('LAB_COMPLETED', 'Lab Tests Completed'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('TREATMENT_PRESCRIBED', 'Treatment Prescribed - Pending Pharmacy Payment'), ('PHARMACY_PAID', 'Pharmacy Payment Completed'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('IN_PHARMACY', 'Currently in Pharmacy'), ('PAYMENT_PENDING', 'Payment Required'), ('COMPLETED', 'Visit Completed'), ('DISCHARGED', 'Discharged')], default='REGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientstatushistory',
            name='new_status',
            field=models.CharField(choices=[('REGISTERED', 'Just Registered'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('WITH_DOCTOR', 'Currently with Doctor'), ('PENDING_LAB_PAYMENT', 'Pending Lab Payment'), ('LAB_PAID', 'Lab Payment Completed'), ('WAITING_LAB', 'Waiting for Lab Tests'), ('IN_LAB', 'Currently in Laboratory'), ('LAB_COMPLETED', 'Lab Tests Completed'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('TREATMENT_PRESCRIBED', 'Treatment Prescribed - Pending Pharmacy Payment'), ('PHARMACY_PAID', 'Pharmacy Payment Completed'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('IN_PHARMACY', 'Currently in Pharmacy'), ('PAYMENT_PENDING', 'Payment Required'), ('COMPLETED', 'Visit Completed'), ('DISCHARGED', 'Discharged')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('REGISTERED', 'Just Registered'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('WITH_DOCTOR', 'Currently with Doctor'), ('PENDING_LAB_PAYMENT', 'Pending Lab Payment'), ('LAB_PAID', 'Lab Payment Completed'), ('WAITING_LAB', 'Waiting for Lab Tests'), ('IN_LAB', 'Currently in Laboratory'), ('LAB_COMPLETED', 'Lab Tests Completed'), ('LAB_RESULTS_READY', 'Lab Results Ready'), ('TREATMENT_PRESCRIBED', 'Treatment Prescribed - Pending Pharmacy Payment'), ('PHARMACY_PAID', 'Pharmacy Payment Completed'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('IN_PHARMACY', 'Currently in Pharmacy'), ('PAYMENT_PENDING', 'Payment Required'), ('COMPLETED', 'Visit Completed'), ('DISCHARGED', 'Discharged')], max_length=20, null=True),
        ),
    ]
