# Generated by Django 4.2.7 on 2025-09-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_portal', '0002_user_approved_at_user_approved_by_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temporary_access_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
