# Generated by Django 4.2.7 on 2025-09-02 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('patients_count', models.IntegerField(default=0)),
                ('appointments_count', models.IntegerField(default=0)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_staff_count', models.IntegerField(default=0)),
                ('scheduled_appointments', models.IntegerField(default=0)),
                ('walk_in_appointments', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('alert_type', models.CharField(choices=[('critical', 'Critical'), ('low_stock', 'Low Stock'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon')], max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['alert_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('maintenance', 'Maintenance')], max_length=20)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name_plural': 'System Status',
                'unique_together': {('service_name',)},
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('patient_admission', 'Patient Admission'), ('staff_update', 'Staff Update'), ('medication_added', 'Medication Added'), ('user_approval', 'User Approval'), ('system_backup', 'System Backup'), ('staff_clockin', 'Staff Clock In'), ('staff_clockout', 'Staff Clock Out')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
