# Generated by Django 4.2.7 on 2025-09-07 05:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Name of the service (e.g., Blood Test, General Consultation)', max_length=200)),
                ('service_code', models.CharField(help_text='Unique code for this service (e.g., LAB001, DOC001)', max_length=20, unique=True)),
                ('service_category', models.CharField(choices=[('CONSULTATION', 'Doctor Consultation'), ('LAB_TEST', 'Laboratory Test'), ('MEDICATION', 'Medication/Pharmacy'), ('NURSING', 'Nursing Service'), ('WARD', 'Ward/Admission'), ('PROCEDURE', 'Medical Procedure'), ('EMERGENCY', 'Emergency Service'), ('OTHER', 'Other Services')], max_length=20)),
                ('description', models.TextField(blank=True, help_text="Detailed description of what's included", null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, help_text='Regular price for this service', max_digits=10)),
                ('emergency_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for emergency/after-hours service', max_digits=10, null=True)),
                ('department', models.CharField(help_text='Which department provides this service', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Average time required for this service', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently offered')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether this service needs admin approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_pricing_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_pricing',
                'ordering': ['service_category', 'service_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(help_text='Unique bill number (BILL20240904001)', max_length=20, unique=True)),
                ('patient_id', models.CharField(help_text='Patient ID (PAT123, etc.)', max_length=20)),
                ('patient_name', models.CharField(help_text='Patient name for reference', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all line items', max_digits=12)),
                ('insurance_covered', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount covered by insurance', max_digits=12)),
                ('patient_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount patient needs to pay', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding amount', max_digits=12)),
                ('bill_status', models.CharField(choices=[('DRAFT', 'Draft - Being Prepared'), ('OPEN', 'Open - Awaiting Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Payment Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('service_date', models.DateField(help_text='Date when services were provided')),
                ('bill_date', models.DateField(auto_now_add=True, help_text='Date when bill was created')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('insurance_provider', models.CharField(blank=True, help_text='Insurance company name', max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, help_text='Insurance policy number', max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_bills',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_date', models.DateField(unique=True)),
                ('consultation_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pharmacy_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lab_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('nursing_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mobile_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bills_created_today', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_start', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_end', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_balanced', models.BooleanField(default=False)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('variance_notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances_approved', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_balances',
                'ordering': ['-balance_date'],
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Name of service provided', max_length=200)),
                ('service_code', models.CharField(help_text='Service code at time of billing', max_length=20)),
                ('service_category', models.CharField(help_text='Category of service', max_length=20)),
                ('quantity', models.IntegerField(default=1, help_text='Number of units of this service')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of service', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity * unit_price', max_digits=10)),
                ('source_department', models.CharField(help_text='Department that provided the service', max_length=20)),
                ('source_reference', models.UUIDField(help_text='ID of the original record (consultation, prescription, etc.)')),
                ('service_date', models.DateTimeField(help_text='When the service was actually provided')),
                ('patient_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.patientbill')),
                ('provided_by', models.ForeignKey(help_text='Staff member who provided the service', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service_pricing', models.ForeignKey(blank=True, help_text='Link to service pricing if available', null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.servicepricing')),
            ],
            options={
                'db_table': 'bill_line_items',
                'ordering': ['service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['service_category'], name='service_pri_service_4670a0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['service_code'], name='service_pri_service_81b649_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepricing',
            index=models.Index(fields=['department'], name='service_pri_departm_f66abd_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['patient_id'], name='patient_bil_patient_c1485a_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['bill_status'], name='patient_bil_bill_st_7de83d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientbill',
            index=models.Index(fields=['bill_date'], name='patient_bil_bill_da_1ebe0c_idx'),
        ),
    ]
