# Generated by Django 4.2.7 on 2025-09-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_service_payment_model'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS service_payments (
                id UUID PRIMARY KEY,
                patient_id VARCHAR(20) NOT NULL,
                patient_name VARCHAR(100) NOT NULL,
                service_type VARCHAR(20) NOT NULL,
                service_name VARCHAR(200) NOT NULL,
                reference_id VARCHAR(50),
                amount DECIMAL(10,2) NOT NULL,
                payment_method VARCHAR(20) DEFAULT 'CASH',
                status VARCHAR(10) DEFAULT 'PENDING',
                payment_date TIMESTAMP WITH TIME ZONE,
                processed_by_id UUID,
                notes TEXT,
                receipt_number VARCHAR(50),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL
            );

            CREATE INDEX IF NOT EXISTS service_pay_patient_53a796_idx ON service_payments (patient_id);
            CREATE INDEX IF NOT EXISTS service_pay_service_e8fb2a_idx ON service_payments (service_type, status);
            CREATE INDEX IF NOT EXISTS service_pay_status_d79984_idx ON service_payments (status, created_at DESC);
            CREATE INDEX IF NOT EXISTS service_pay_payment_3ffc00_idx ON service_payments (payment_date);
            """,
            reverse_sql="DROP TABLE IF EXISTS service_payments;"
        )
    ]
