# Generated by Django 4.2.7 on 2025-09-29 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='labtestrequest',
            name='lab_test_re_urgency_facf41_idx',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='test_description',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='labtestrequest',
            name='urgency',
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='Free-form clinical notes as in hospital form', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Consultation fee in TZS', max_digits=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee_paid_by',
            field=models.ForeignKey(blank=True, help_text='Staff who processed payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_fee_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medication_plan',
            field=models.TextField(blank=True, help_text='Medication plan and prescriptions', null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='possible_diagnosis',
            field=models.TextField(blank=True, help_text='Possible/differential diagnosis', null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='blood_grouping_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='blood_grouping_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='bs_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='bs_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='esr_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='esr_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='fbg_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='fbg_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='h_pylori_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='h_pylori_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hb_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hb_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hepatitis_b_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hepatitis_b_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hepatitis_c_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='hepatitis_c_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='investigation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total lab fee based on requested tests', max_digits=10),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_fee_paid_by',
            field=models.ForeignKey(blank=True, help_text='Staff who processed payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_fee_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='lab_fee_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='mrdt_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='mrdt_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient_sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rbg_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rbg_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='reported_by',
            field=models.CharField(blank=True, help_text='Lab technician name who reported results', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rheumatoid_factor_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rheumatoid_factor_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rpr_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='rpr_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='short_clinical_notes',
            field=models.TextField(blank=True, help_text='Short clinical notes for lab', null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sickling_test_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='sickling_test_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='signature',
            field=models.CharField(blank=True, help_text='Lab technician signature', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='ssat_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='ssat_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='stool_analysis_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='stool_macro_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='stool_micro_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='upt_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='upt_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_bilirubin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_blood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_glucose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_ketones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_leucocytes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_nitrite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_ph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_protein',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_sg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urinalysis_urobilinogen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urine_sed_macro_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urine_sed_micro_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='urine_sed_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True, default='', help_text='Medical diagnosis'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True, default='', help_text='Patient symptoms and history'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True, default='', help_text='Treatment recommendations'),
        ),
        migrations.AlterField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('REQUESTED', 'Test Requested'), ('IN_PROGRESS', 'Test In Progress'), ('COMPLETED', 'Test Completed'), ('CANCELLED', 'Test Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='labtestrequest',
            index=models.Index(fields=['patient_id'], name='lab_test_re_patient_8c036d_idx'),
        ),
    ]
