# Generated by Django 4.2.7 on 2025-09-30 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_add_clinical_notes_and_enhanced_lab_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory rate (breaths per minute)', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
