# Generated by Django 4.2.7 on 2025-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_consultation_respiratory_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='general_advice',
            field=models.TextField(
                blank=True,
                default='',
                help_text='General advice to patient (e.g., rest, exercise, diet, hydration)'
            ),
        ),
    ]
