# Generated by Django 4.2.7 on 2025-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_add_prescription_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='general_advice',
            field=models.TextField(blank=True, default='', help_text='General lifestyle/behavioral advice (e.g., rest, exercise, diet, hydration) - separate from medication prescriptions'),
        ),
    ]
