# Generated by Django 4.2.7 on 2025-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_consultation_general_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication_id',
            field=models.UUIDField(blank=True, help_text='Link to pharmacy.Medication model if from database', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit in TZS (from Medication database)', max_digits=10, null=True),
        ),
    ]
