CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "staff" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(150) NOT NULL,
  "role_id" int,
  "username" varchar(100) UNIQUE,
  "password_hash" varchar(255),
  "contact_info" text,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "patients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(150) NOT NULL,
  "dob" date,
  "gender" varchar(10),
  "contact_info" text,
  "emergency_contact" text,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "appointments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "doctor_id" int,
  "appointment_time" datetime NOT NULL,
  "reason" text,
  "status" varchar(50) DEFAULT 'scheduled'
);

CREATE TABLE "treatments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int,
  "description" text,
  "treatment_date" datetime NOT NULL,
  "cost" decimal(10,2) DEFAULT 0
);

CREATE TABLE "medications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "stock_quantity" int DEFAULT 0,
  "unit_price" decimal(10,2) DEFAULT 0
);

CREATE TABLE "prescriptions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "treatment_id" int,
  "medication_id" int,
  "quantity" int NOT NULL,
  "dosage" varchar(100)
);

CREATE TABLE "billing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "created_by" int,
  "total_amount" decimal(10,2) NOT NULL,
  "paid_amount" decimal(10,2) DEFAULT 0,
  "balance" decimal(10,2) DEFAULT 0,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "billing_id" int,
  "received_by" int,
  "amount" decimal(10,2) NOT NULL,
  "payment_method" varchar(50),
  "payment_date" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "suppliers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) UNIQUE NOT NULL,
  "contact_info" text
);

CREATE TABLE "expenses_internal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recorded_by" int,
  "description" text,
  "amount" decimal(10,2) NOT NULL,
  "expense_date" date NOT NULL
);

CREATE TABLE "expenses_supply" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "recorded_by" int,
  "description" text,
  "amount" decimal(10,2) NOT NULL,
  "expense_date" date NOT NULL
);

CREATE TABLE "creditors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" int,
  "amount" decimal(10,2) NOT NULL,
  "due_date" date
);

CREATE TABLE "debtors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "amount" decimal(10,2) NOT NULL,
  "due_date" date
);

CREATE TABLE "salaries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" int,
  "amount" decimal(10,2) NOT NULL,
  "salary_date" date NOT NULL
);

CREATE TABLE "reports" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_type" varchar(50) NOT NULL,
  "data" json,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

ALTER TABLE "staff" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("doctor_id") REFERENCES "staff" ("id");

ALTER TABLE "treatments" ADD FOREIGN KEY ("appointment_id") REFERENCES "appointments" ("id");

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("treatment_id") REFERENCES "treatments" ("id");

ALTER TABLE "prescriptions" ADD FOREIGN KEY ("medication_id") REFERENCES "medications" ("id");

ALTER TABLE "billing" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "billing" ADD FOREIGN KEY ("created_by") REFERENCES "staff" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("billing_id") REFERENCES "billing" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("received_by") REFERENCES "staff" ("id");

ALTER TABLE "expenses_internal" ADD FOREIGN KEY ("recorded_by") REFERENCES "staff" ("id");

ALTER TABLE "expenses_supply" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id");

ALTER TABLE "expenses_supply" ADD FOREIGN KEY ("recorded_by") REFERENCES "staff" ("id");

ALTER TABLE "creditors" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id");

ALTER TABLE "debtors" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id");

ALTER TABLE "salaries" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("id");
