# Generated by Django 4.2.7 on 2025-09-04 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_request_id', models.CharField(help_text='UUID of LabTestRequest from doctor app', max_length=36)),
                ('patient_id', models.CharField(help_text='Patient ID (PAT123, etc.)', max_length=20)),
                ('patient_name', models.CharField(help_text='Patient name for quick reference', max_length=100)),
                ('test_type', models.CharField(help_text='Type of test performed', max_length=50)),
                ('test_description', models.TextField(help_text='Original test description from doctor')),
                ('result_summary', models.TextField(help_text='Main test results summary')),
                ('result_details', models.TextField(blank=True, help_text='Detailed results if needed', null=True)),
                ('normal_range', models.CharField(blank=True, help_text='Normal range for this test', max_length=200, null=True)),
                ('result_status', models.CharField(choices=[('IN_PROGRESS', 'Test In Progress'), ('COMPLETED', 'Test Completed'), ('ABNORMAL', 'Abnormal Results'), ('CRITICAL', 'Critical Results - Urgent')], default='COMPLETED', max_length=15)),
                ('urgent_flag', models.BooleanField(default=False, help_text='Mark as urgent if results need immediate doctor attention')),
                ('technician_notes', models.TextField(blank=True, help_text='Additional notes from lab technician', null=True)),
                ('result_image', models.ImageField(blank=True, help_text='Image of test results (X-ray, etc.)', null=True, upload_to='lab_results/')),
                ('test_started_at', models.DateTimeField(auto_now_add=True)),
                ('test_completed_at', models.DateTimeField(auto_now=True)),
                ('doctor_notified', models.BooleanField(default=False, help_text='Whether doctor has been notified of results')),
                ('doctor_viewed', models.BooleanField(default=False, help_text='Whether doctor has viewed the results')),
                ('processed_by', models.ForeignKey(limit_choices_to={'role': 'LAB'}, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_test_results',
                'ordering': ['-test_completed_at'],
                'indexes': [models.Index(fields=['lab_request_id'], name='lab_test_re_lab_req_245be5_idx'), models.Index(fields=['patient_id'], name='lab_test_re_patient_e54f10_idx'), models.Index(fields=['result_status', '-test_completed_at'], name='lab_test_re_result__e2311b_idx'), models.Index(fields=['urgent_flag', '-test_completed_at'], name='lab_test_re_urgent__e55614_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_title', models.CharField(help_text='Brief description of order', max_length=200)),
                ('items_list', models.TextField(help_text='List of items needed (simple text format for now)')),
                ('justification', models.TextField(help_text='Why these items are needed')),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent - Out of Stock')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Order'), ('SUBMITTED', 'Submitted to Pharmacy'), ('APPROVED', 'Approved'), ('COMPLETED', 'Order Completed'), ('CANCELLED', 'Order Cancelled')], default='DRAFT', max_length=15)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total cost in TZS', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(limit_choices_to={'role': 'LAB'}, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='lab_orders_status_f97a57_idx'), models.Index(fields=['priority', '-created_at'], name='lab_orders_priorit_9819b2_idx')],
            },
        ),
    ]
